language: r

r_github_packages:
  - rstudio/leaflet
  - rstudio/shinydashboard
  - rstudio/bookdown

r_packages:
  - ggplot2
  - devtools
  - dplyr
  - tidyr
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  
sudo: false
