language: r

r_packages:
  - ggplot2
  - devtools
  - dplyr
  - tidyr

r_github_packages:
  - rstudio/bookdown

install: 
  - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  
sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files  