language: r
sudo: false
r_packages:
  - ggplot2
  - devtools
  - dplyr
  - tidyr
  - leaflet

r_github_packages:
  - rstudio/bookdown
  - rstudio/shinydashboard
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
