language: r

r_packages:
  - ggplot2
  - devtools
  - dplyr
  - tidyr

r_github_packages:
  - rstudio/leaflet
  - rstudio/shinydashboard
  - rstudio/bookdown

install: true
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  
sudo: false

cache:
  packages: no
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files  